image:
  file: .gitpod.Dockerfile
tasks:
  - init: npm install
    command: |
      export CLIENT_URL="$(gp url 35729)/livereload.js?snipver=1&port=443"
      npm run bootstrap
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 10000
    onOpen: ignore
