image:
  file: .gitpod.Dockerfile
tasks:
  - init: npm install
    command: npm run bootstrap
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 10000
    onOpen: ignore
